In [2]:
from pycaret.datasets import get_data
from pycaret.classification import *

#в моєму варіанті 16, мав використовуватись датасет churn, але get_data не може його знайти
data = get_data('us_presidential_election_results')
print(data.head())
#тому як наш датасет містить результати президентських виборів, то це є завданням
#класифікації (win or loose).

#робимо сетап експерименту класифікації з цільовою змінною party_winner
exp = setup(data, target='party_winner', session_id=123)

#Порівнюємо продуктивність різних моделей класифікації і обираємо найкращу модель
best_model = compare_models()

#Робимо прогноз на основі обраної моделі і датасету
predictions = predict_model(best_model, data=data)

#виводимо результат. 
#Результатом коду будуть прогнозовані класи та ймовірності для нашого набору даних
print(predictions.head())
# Save best model
save_model(best_model, 'best_model')

,cycle,state,dem_poll_avg,dem_poll_avg_margin,incumbent_party,incumbent_running,party_winner
0,1976,California,42.797994,-3.270222,republican,1,republican
1,1976,Colorado,42.180101,-1.373191,republican,1,republican
2,1976,Connecticut,41.698014,-1.469654,republican,1,republican
3,1976,Delaware,33.370748,2.445322,republican,1,democrat
4,1976,Georgia,59.796546,29.379760,republican,1,democrat

   cycle        state  dem_poll_avg  dem_poll_avg_margin incumbent_party  \
0   1976   California     42.797994            -3.270222      republican
1   1976     Colorado     42.180101            -1.373191      republican
2   1976  Connecticut     41.698014            -1.469654      republican
3   1976     Delaware     33.370748             2.445322      republican
4   1976      Georgia     59.796546            29.379760      republican

   incumbent_running party_winner
0                  1   republican
1                  1   republican
2                  1   republican
3                  1     democrat
4                  1     democrat

   cycle        state  dem_poll_avg  dem_poll_avg_margin incumbent_party  \
0   1976   California     42.797993            -3.270222      republican
1   1976     Colorado     42.180099            -1.373191      republican
2   1976  Connecticut     41.698013            -1.469654      republican
3   1976     Delaware     33.370747             2.445322      republican
4   1976      Georgia     59.796547            29.379761      republican

   incumbent_running party_winner prediction_label  prediction_score
0                  1   republican       republican               1.0
1                  1   republican       republican               0.8
2                  1   republican       republican               0.8
3                  1     democrat         democrat               0.6
4                  1     democrat         democrat               1.0
Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=FastMemory(location=/tmp/joblib),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['cycle', 'dem_poll_avg',
                                              'dem_poll_avg_margin',
                                              'incumbent_running'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_va...
                  TransformerWrapper(exclude=None, include=['state'],
                                     transformer=LeaveOneOutEncoder(cols=['state'],
                                                                    drop_invariant=False,
                                                                    handle_missing='return_nan',
                                                                    handle_unknown='value',
                                                                    random_state=123,
                                                                    return_df=True,
                                                                    sigma=None,
                                                                    verbose=0))),
                 ('trained_model',
                  KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                       metric='minkowski', metric_params=None,
                                       n_jobs=-1, n_neighbors=5, p=2,
                                       weights='uniform'))],
          verbose=False),
 'best_model.pkl')

In [3]:
predictions

,cycle,state,dem_poll_avg,dem_poll_avg_margin,incumbent_party,incumbent_running,party_winner,prediction_label,prediction_score
0,1976,California,42.797993,-3.270222,republican,1,republican,republican,1.0
1,1976,Colorado,42.180099,-1.373191,republican,1,republican,republican,0.8
2,1976,Connecticut,41.698013,-1.469654,republican,1,republican,republican,0.8
3,1976,Delaware,33.370747,2.445322,republican,1,democrat,democrat,0.6
4,1976,Georgia,59.796547,29.379761,republican,1,democrat,democrat,1.0
...,...,...,...,...,...,...,...,...,...
492,2016,Virginia,47.267189,5.412200,democrat,0,democrat,republican,0.6
493,2016,Washington,50.271080,15.181010,democrat,0,democrat,democrat,1.0
494,2016,West Virginia,28.617830,-27.234200,democrat,0,republican,republican,1.0
495,2016,Wisconsin,46.565559,4.916080,democrat,0,republican,republican,0.6
496,2016,Wyoming,22.079571,-37.877419,democrat,0,republican,republican,1.0